version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - my_network
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks: 
      - my_network
    env_file:
      - ./frontend/.env

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
